In [3]:
import numpy as np

# Basics

In [4]:
a = np.array([1, 2, 3]) 

In [6]:
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8,7,10], [9.0, 1.0, 2.0,5.0]])

In [10]:
print(b)

[[ 9.  8.  7. 10.]
 [ 9.  1.  2.  5.]]


In [11]:
# git number of dimention
a.ndim

1

In [12]:
b.ndim

2

In [13]:
# get shape
a.shape

(3,)

In [14]:
b.shape

(2, 4)

In [15]:
# get Type
a.dtype

dtype('int32')

In [19]:
c = np.array([1,2,3], dtype='int32')

In [20]:
c.dtype

dtype('int32')

In [21]:
# get size 
c.itemsize

4

In [22]:
#get total size
a.nbytes

12

In [23]:
# b is 8 because it is float
b.itemsize

8

In [25]:
b.nbytes # 8 * 8

64

# Accessing/Changing Specific elements, row, columns 

In [26]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [27]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
a.shape

(2, 7)

In [29]:
a[0, 5]

6

In [30]:
a[1, 6]

14

In [31]:
a[1, -1]

14

In [32]:
a[0, -2]

6

In [33]:
# get specific row
print(a[0, :])

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
print(a[1, :])

[ 8  9 10 11 12 13 14]


In [36]:
# get specific column
print(a[:, 2])

[ 3 10]


In [37]:
print(a[:, -1])

[ 7 14]


In [38]:
print(a[:, -2])

[ 6 13]


In [39]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [44]:
print(a[0, 1:6:2])

[2 4 6]


In [46]:
print(a[0, 1:-1:2])

[2 4 6]


In [47]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [51]:
a[:, 2] =5 
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [52]:
a[:, 5] = [30, 40]
print(a)

[[ 1  2  5  4  5 30  7]
 [ 8  9  5 11 12 40 14]]


# 3d example

In [53]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [54]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# get specific element
b[0, :, :]

array([[1, 2],
       [3, 4]])

In [57]:
b[0, 1, :]

array([3, 4])

In [58]:
b[-1]

array([[5, 6],
       [7, 8]])

In [59]:
# replace
b[:, 1, :] = [[9,9], [8,8]]

In [60]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Type of Array

In [61]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
np.zeros((2,2), dtype='int')

array([[0, 0],
       [0, 0]])

In [67]:
# All 0s matrix
np.ones((2, 3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [68]:
# Any other number
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [70]:
np.full((2, 2), 7, dtype='float32')

array([[7., 7.],
       [7., 7.]], dtype=float32)

In [71]:
# Any other number (full_like)
np.full_like(a, 9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [72]:
np.full(a.shape, 9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [75]:
# random decimals numbers
np.random.rand(4, 3)

array([[0.35650618, 0.41143966, 0.02485841],
       [0.03122603, 0.11840756, 0.6102174 ],
       [0.76930689, 0.06221998, 0.11549342],
       [0.86223913, 0.83123327, 0.56118882]])

In [81]:
np.random.random_sample(a.shape)

array([[0.54345561, 0.64402109, 0.23427873, 0.83480131, 0.4659404 ,
        0.28123525, 0.09198176],
       [0.03467995, 0.25248251, 0.19982881, 0.94103269, 0.02466124,
        0.4778161 , 0.38147757]])

In [90]:
# random integer values
np.random.randint(1, 10, 5)

array([1, 7, 5, 9, 5])

In [92]:
np.random.randint(1, 10, (2, 2))

array([[2, 9],
       [8, 4]])

In [95]:
# identity matrix must be squre
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.identity(3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [106]:
# repeat an array
arr = np.array([[1,2,3]]) 
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [107]:
arr = np.array([[1,2,3]]) 
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [114]:
out = np.ones((5, 5))
out[1:4, 1:4] = np.zeros(3)
out[2, 2] = 9
print(out)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be Careful when copying array 

In [122]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

In [123]:
b

array([100,   2,   3])

In [124]:
a

array([1, 2, 3])

# Mathematics

In [133]:
a = np.array([1,2,3,4])

In [134]:
a + 2

array([3, 4, 5, 6])

In [135]:
a - 2

array([-1,  0,  1,  2])

In [136]:
a * 2

array([2, 4, 6, 8])

In [137]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [138]:
b = np.array([1,0,1,0])

In [139]:
a + b

array([2, 2, 4, 4])

In [140]:
a - b

array([0, 2, 2, 4])

In [144]:
a * b

array([1, 0, 3, 0])

In [141]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [143]:
# tale the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Liner Algebra

In [151]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [152]:
c = np.identity(3)
np.linalg.det(c)

1.0

#  statistics

In [153]:
stats = np.array([[1,2,3], [4,5,6]])

In [155]:
np.min(stats)

1

In [156]:
np.max(stats)

6

In [157]:
# get min number from each column
np.min(stats, axis=0)

array([1, 2, 3])

In [159]:
# get max number from each row
np.max(stats, axis=1)

array([3, 6])

In [161]:
np.sum(stats)

21

In [162]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [163]:
np.sum(stats, axis=1)

array([ 6, 15])

#  Reorganizing arrays

In [165]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [166]:
before.shape

(2, 4)

In [167]:
before.reshape(8, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [168]:
before.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [169]:
before.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [172]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [177]:
# horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Advanced indexing

In [188]:
df = np.random.randint(1, 200, size=(3, 18))

In [189]:
df

array([[134, 184, 112, 105, 166, 157,  53,  20, 138,  81,  40, 185,  27,
        194,  31, 180, 160,  42],
       [177,  37, 162, 136,  37, 152,  87, 193, 130, 112,  44,  25, 181,
         48, 127, 158, 174, 170],
       [155,   7,  70,  33,  64, 151,  57,  79, 144, 190,  82, 136, 168,
        163, 183,  93,  21,  76]])

In [190]:
df > 50

array([[ True,  True,  True,  True,  True,  True,  True, False,  True,
         True, False,  True, False,  True, False,  True,  True, False],
       [ True, False,  True,  True, False,  True,  True,  True,  True,
         True, False, False,  True, False,  True,  True,  True,  True],
       [ True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True]])

In [191]:
df[df > 60]

array([134, 184, 112, 105, 166, 157, 138,  81, 185, 194, 180, 160, 177,
       162, 136, 152,  87, 193, 130, 112, 181, 127, 158, 174, 170, 155,
        70,  64, 151,  79, 144, 190,  82, 136, 168, 163, 183,  93,  76])

In [192]:
np.any(df > 50)

True

In [193]:
np.all(df > 50)

False

In [194]:
np.any(df > 50, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [195]:
np.all(df > 50, axis=0)

array([ True, False,  True, False, False,  True,  True, False,  True,
        True, False, False, False, False, False,  True, False, False])